export type Story = {
 slug:string; title:string; description:string; destination:string; category:string; author:string; authorSlug:string;
 published:string; updated:string; image:string; readTime:string; intro:string; sections:{heading:string;body:string}[];
};
export const creators = {
 "infio2-editorial": {name:"InfiO2 Editorial Team",role:"Travel planning & destination research",bio:"The InfiO2 editorial team creates practical destination guidance designed to help travelers move from inspiration to a personalized trip plan."},
 "guest-creator": {name:"Guest Travel Creator",role:"Independent travel contributor",bio:"Independent contributors share first-hand destination perspectives. Contributor opinions are their own and are reviewed for clarity and disclosure before publication."}
};
export const stories:Story[]=[
 {slug:"rome-florence-venice-first-trip",title:"Rome, Florence & Venice: A First-Timer’s Italy Route",description:"A practical framework for dividing 9–10 days among three classic Italian cities without turning the vacation into a race.",destination:"Italy",category:"Itineraries",author:"InfiO2 Editorial Team",authorSlug:"infio2-editorial",published:"2026-08-30",updated:"2026-08-30",image:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1400&q=82",readTime:"6 min",intro:"Italy rewards slower travel. For many first visits, Rome, Florence and Venice provide a strong combination of history, food, art and atmosphere while keeping the route manageable.",sections:[
 {heading:"How to divide the time",body:"A balanced 9–10 day framework is roughly three nights in Rome, two or three in Florence and two or three in Venice, allowing for arrival and departure logistics. Add nights rather than attractions when you want a more relaxed pace."},
 {heading:"What to protect in the schedule",body:"Reserve timed attractions carefully and protect unscheduled blocks for neighborhoods, meals and spontaneous discoveries. Avoid placing every major museum and landmark on consecutive half-days."},
 {heading:"Make the route personal",body:"Families may prioritize shorter touring blocks; food-focused travelers may add markets and cooking experiences; couples may prefer an extra evening in Florence or Venice. Your itinerary should reflect how you actually like to travel."}]},
 {slug:"japan-first-trip-planning-guide",title:"Planning a First Trip to Japan: Tokyo, Kyoto and Beyond",description:"Plan a first trip to Japan with practical guidance on Tokyo, Kyoto, rail travel, trip pacing, neighborhood choices and time for independent exploring.",destination:"Japan",category:"Destination Guides",author:"InfiO2 Editorial Team",authorSlug:"infio2-editorial",published:"2026-08-30",updated:"2026-08-30",image:"https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1400&q=82",readTime:"7 min",intro:"Japan can support very different trips, from high-energy city exploration to temples, food, nature and onsen stays. Good planning starts with choosing fewer bases and giving each enough time.",sections:[
 {heading:"Start with the route",body:"Tokyo and Kyoto form a useful first-trip backbone. Osaka, Hakone, Hiroshima or other regions can be added when the trip length and traveler interests justify the extra movement."},
 {heading:"Balance reservations and discovery",body:"Some attractions and restaurants benefit from advance planning, but an itinerary should still preserve time to explore neighborhoods without a checklist."},
 {heading:"Check current rules before departure",body:"Transport products, attraction procedures and entry requirements can change. Verify important operational details with the relevant official source close to travel."}]},
 {slug:"family-vacation-with-free-time",title:"Why Family Vacations Need More Free Time Than You Think",description:"Plan a better-paced family vacation with realistic sightseeing, rest time, meals, transit and flexible moments that help the whole family enjoy the trip.",destination:"Worldwide",category:"Family Travel",author:"InfiO2 Editorial Team",authorSlug:"infio2-editorial",published:"2026-08-30",updated:"2026-08-30",image:"https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1400&q=82",readTime:"5 min",intro:"The best family itinerary is rarely the one with the longest attraction list. Transit, meals, weather, sleep and different energy levels all compete with sightseeing.",sections:[
 {heading:"Plan around energy, not only geography",body:"A geographically efficient day can still be exhausting. Alternate major sightseeing blocks with parks, beaches, pools, cafés or unstructured neighborhood time."},
 {heading:"Build optionality into the plan",body:"Label some experiences optional rather than mandatory. That gives families room to respond to weather, fatigue and changing interests without feeling that the trip has failed."},
 {heading:"Use the itinerary as a framework",body:"A preliminary itinerary should make decisions easier, not lock travelers into every hour. Keep the most important reservations firm and the rest adaptable."}]}
];
export const storyBySlug=(slug:string)=>stories.find(s=>s.slug===slug);
